
name: Add Release Build

on: release

jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build
      run: |
        python build.py
    - name: Add built files to release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: build.zip
